NOISSUE - Add MQTTS zephyrs target.
mainflux/embedded pull request #8
Opened 2023-08-28 11:20 UTC by 1998-felix

### What does this do?
Use zephyr to enable mqtts for stm32f4 target

### Which issue(s) does this PR fix/relate to?
https://github.com/ultravioletrs/issues/issues/287

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes

2023-09-15 12:55 UTC, drasko requested changes

2023-09-15 12:55 UTC, drasko commented on targets/zephyr_targets/mqtts/src/config.h
> +char mfTopic[150];
Why 50? Magic number? Also, keep these numbers a power of two, 128 or 256 makes much more sense probably - unless this length is derived from MQTT standard, but then you need to explain this in the topic and reference exact standard chapter (provide the link as well). Use `DEFINE`.

2023-09-15 13:27 UTC, rodneyosodo requested changes

2023-09-15 13:27 UTC, rodneyosodo commented on targets/zephyr_targets/mqtts/.gitignore
> +src/creds
Add new line

2025-01-12 16:23 UTC, drasko approved these changes
LGTM

2025-01-12 16:23 UTC, merged